class Config:
    DEFAULT_REGION_NAME = "ap-northeast-1"

    DEFAULT_GENERATIVE_MODEL_ID = "deepseek.v3-v1:0"
    DEFAULT_GENERATIVE_MODEL_IPPT = 0.000701666
    DEFAULT_GENERATIVE_MODEL_OPPT = 0.002032411

    DEFAULT_EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"
    DEFAULT_EMBEDDING_DIMENSIONS = 1024
