class Config:
    DEFAULT_REGION_NAME = "ap-northeast-1"

    DEFAULT_GENERATIVE_MODEL_ID = "jp.anthropic.claude-haiku-4-5-20251001-v1:0"
    DEFAULT_GENERATIVE_MODEL_IPPT = 0.001
    DEFAULT_GENERATIVE_MODEL_OPPT = 0.005

    DEFAULT_EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"
    DEFAULT_EMBEDDING_DIMENSIONS = 1024

    DEFAULT_DISCORD_EMBED_COLOR = 0x743D90
